const frogs = {
    desertRainFrog: {
        id: 1,
        commonName: "Dessert rain frog",
        scientificName: "Breviceps macrops",
        imgSrc: "https://factanimal.com/wp-content/uploads/2023/02/desert-rain-frog-facts.jpg",
        info: "The desert rain frog is a plump species with bulging eyes, a short snout, short limbs, spade-like feet, and webbed toes",
    },
    blackRainFrog: {
        id: 2,
        commonName: "Black rain frog",
        scientificName: "Breviceps fuscus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Black_Rain_Frog_imported_from_iNaturalist_photo_15409543.jpg",
        info: "At night the black rain frog emerges from its burrow to scavenge for food and sometimes mate.",
    },
    americanBullFrog: {
        id: 3,
        commonName: "American bullfrog",
        scientificName: "Lithobates catesbeianus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/4/4a/American_Bullfrog_Rana_catesbeiana_Front_838px.jpg",
        info: "The bullfrog gets its name from the sound the male makes during the breeding season, which sounds similar to a bull bellowing.",
    },
    purpleFrog: {
        id: 4,
        commonName: "Purple frog",
        scientificName: "Nasikabatrachus sahyadrensis",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/0/08/Nasikabatrachus_sahyadrensis.jpg",
        info: "Its vocalization is a drawn-out harsh call that sounds similar to a chicken clucking. Males of this species exhibit the unique behavior of calling from under a thin layer of soil.",
    },
    cranwellsHornedFrog: {
        id: 5,
        commonName: "Cranwell's horned frog",
        scientificName: "Ceratophrys cranwelli",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Pacman_frog.jpg/1024px-Pacman_frog.jpg",
        info: "Is commonly called the Pac-man frog, because of its resemblance to the video game character of the same name. The specific name, cranwelli, is in honor of Argentinian herpetologist Jorge A. Cranwell",
    },
    mossyFrog: {
        id: 6,
        commonName: "Mossy frog",
        scientificName: "Theloderma corticale",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Theloderma_corticale_-_Karlsruhe_Zoo_01.jpg",
        info: "Its skin is a mottled green and brown that resembles moss growing on rock, and forms an effective form of camouflage.",
    },
    glassFrog: {
        id: 7,
        commonName: "Glass frog",
        scientificName: "Centrolenidae",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Cochranella_susatamai03.jpg",
        info: "The abdominal skin of some members of this family is transparent and translucent, giving the glass frog its common name. The internal viscera, including the heart, liver, and gastrointestinal tract, are visible through the skin.",
    },
    africanDwarfFrog: {
        id: 8,
        commonName: "African dwarf frog",
        scientificName: "Hymenochirus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/2/23/African_dwarf_frog.jpg",
        info: "African dwarf frogs live their entire lives underwater, but need to rise to the surface to breathe air as they have lungs and not gills. These frogs are small in size and do not weigh more than a few grams.",
    },
    budgettsFrog: {
        id: 9,
        commonName: "Budgett's frog",
        scientificName: "Lepidobatrachus laevis",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/9/92/Lepidobatrachus_laevis.jpg",
        info: "This frog has become popular in pet stores due to its comical flat appearance and intelligent behavior.",
    },
    amazonMilkFrog: {
        id: 10,
        commonName: "Amazon milk frog",
        scientificName: "Trachycephalus resinifictrix",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/1/12/Amazon_Milk_Frog_%28Trachycephalus_resinifictrix%29%2C_CMN.jpg",
        info: "Their blood tends to be a shade of blue which can be shown through their skin, most boldly in the mouth area and toe pads. The \"milk\" in the common name comes from the milky fluid these frogs excrete when stressed.",
    },
    coquiFrog: {
        id: 11,
        commonName: "Coqui",
        scientificName: "Eleutherodactylus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Common_Coqu%C3%AD.jpg",
        info: "Coqui frogs are small tree frogs. They can range in size from 15–80 millimetres",
    },
    barkingTreeFrog: {
        id: 12,
        commonName: "Barking tree frog",
        scientificName: "Dryophytes gratiosus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/5/54/Hyla_gratiosa_UMFS_2014_2.JPG",
        info: "The barking tree frog is known for its loud, strident, barking call. It may also utter a repetitive single-syllable mating call. It has been known to chorus with other frogs of the same and similar species.",
    },
    darwinsFrog: {
        id: 13,
        commonName: "Darwin's frog",
        scientificName: "Rhinoderma darwinii",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/f/f1/Ranita_de_Darwin_%28Rhinoderma_darwinii%29.png",
        info: "Darwin’s frog is most known for its unique method of brooding. The male will facilitate development of its tadpoles inside its vocal sac.",
    },
    moorFrog: {
        id: 14,
        commonName: "Moor frog",
        scientificName: "Rana arvalis",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Rana_arvalis2.jpg",
        info: "Moor frogs are known for their ability to freeze solid and survive thawing. The frog makes use of various cryoprotectants i.e. antifreeze that decrease its internal freezing temperature. Male moor frogs are known to turn blue temporarily during the height of mating season.",
    },
    longNosedHornedFrog: {
        id: 15,
        commonName: "Long nosed horned frog",
        scientificName: "Pelobatrachus nasutus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/2/2f/Megophrys.nasuta.7034.jpg",
        info: " The upper eyelids and snout are drawn out into long triangular projections, forming what looks like \"horns\", giving them their common name.",
    },
    chocolateFrog: {
        id: 16,
        commonName: "Chocolate frog",
        scientificName: "Ranoidea mira",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/1/19/F371d04b8aa7329b51cbba7d0ff0a9a11604c1910a6371e773307c8e260cec2b.0.jpg",
        info: "Ranoidea mira bears a close resemblance with the Australian green tree frog. They both look similar apart from their skin color. Ranoidea mira has a combination of webbing on hand, large size, limbs that are relatively short and robust as well as small violet patch of skin present on the edges of its eyes.",
    },
    dancingFrog: {
        id: 17,
        commonName: "Dancing frog",
        scientificName: "Micrixalus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Micrixalus_foot_flagging.jpg",
        info: "Males tap their hindfeet and extend it, subsequently stretching the foot outward and shaking it, both at prospective mates and rival males",
    },
    indianBullfrog: {
        id: 18,
        commonName: "Indian bullfrog",
        scientificName: "Hoplobatrachus tigerinus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/5/56/Hoplobatrachus_tigerinus%2CAlapuzha.jpg",
        info: "Normally green or brown with dark spots, males turn yellow during the breeding season. They tend to have a yellow streak along the spinal region of their back.",
    },
    caneFrog: {
        id: 19,
        commonName: "Cane frog",
        scientificName: "Rhinella marina",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/d/dd/Cane-toad.jpg",
        info: "The cane toad has poison glands, and the tadpoles are highly toxic to most animals if ingested. Its toxic skin can kill many animals, both wild and domesticated, and cane toads are particularly dangerous to dogs.",
    },
    orientalFireBelliedToad: {
        id: 20,
        commonName: "Oriental fire bellied toad",
        scientificName: "Bombina orientalis",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/9/98/Bombina_orientalis_Gen%C3%A8ve_24102014.jpg",
        info: "Oriental fire-bellied toads can be bright, grayish, or brownish green, with black mottling on their dorsal regions",
    },
    europeanFireBelliedToad: {
        id: 21,
        commonName: "European fire bellied toad",
        scientificName: "Bombina bombina",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/3/31/Bombina_bombina_1_%28Marek_Szczepanek%29.jpg",
        info: "The dorsal coloration can vary from gray to brown to green, while the stomach is red with thick black mottling. The backs of these frogs are covered in warts. ",
    },
    pumpkinToadlet: {
        id: 22,
        commonName: "Pumpkin toadlet",
        scientificName: "Brachycephalus ephippium",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/5/56/Brachycephalus_ephippium02.jpg",
        info: "Peculiarly, this species and the closely related red pumpkin toadlet are unable to hear the frequency of their own advertising calls, as their ears are underdeveloped. Instead their communication appears to rely on certain movements like the vocal sac that inflates when calling, mouth gaping and waving of their arms.",
    },
    hairyFrog: {
        id: 23,
        commonName: "Hairy frog",
        scientificName: "Trichobatrachus robustus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/2/24/Trichobatrachus_robustus.JPG",
        info: "Also known as the horror frog or Wolverine frog. Breeding males also develop hair-like dermal papillae that extend along the flanks and thighs. These contain arteries and are thought to increase the surface area for the purpose of absorbing oxygen.",
    },
    tomatoFrog: {
        id: 24,
        commonName: "Tomato frog",
        scientificName: "Dyscophus antongilii",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/c/c2/TomatoFrog.jpg",
        info: "When threatened, a tomato frog puffs up its body. When a predator grabs a tomato frog in its mouth, the frog's skin secretes a thick substance that numbs up the predator's eyes and mouth, causing the predator to release the frog to free up its eyes.",
    },
    wallacesFlyingFrog: {
        id: 25,
        commonName: "Wallace's flying frog",
        scientificName: "Rhacophorus nigropalmatus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/4/45/Rhacophorus_nigropalmatus.jpg",
        info: "When threatened or in search of prey, they will leap from a branch and splay their four webbed feet. The membranes between their toes and loose skin flaps on their sides catch the air as they fall, helping them to glide, sometimes 50 feet (15 meters) or more, to a neighboring tree branch or even all the way to the ground.",
    },
    poisonDartFrog: {
        id: 26,
        commonName: "Poison dart frog",
        scientificName: "Dendrobatidae",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Ranitomeya_amazonica.jpg",
        info: "Most poison dart frogs are brightly colored, displaying aposematic patterns to warn potential predators. Their bright coloration is associated with their toxicity and levels of alkaloids.",
    },
    redEyedTreeFrog: {
        id: 27,
        commonName: "Red eyed tree frog",
        scientificName: "Agalychnis callidryas",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Red-eyed_Tree_Frog_%28Agalychnis_callidryas%29_1.png",
        info: "Males attract females by croaking and wrestle with each other in male-male competition in order to gain access to females for reproduction.",
    },
    spinyHeadedTreeFrog: {
        id: 28,
        commonName: "Spiny headed tree frog",
        scientificName: "Triprion spinosus",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/3/3c/Anotheca_spinosa_-_crowned_treefrog_%2812666427385%29.jpg",
        info: "It has numerous sharp, pointed projections on the head and dorsal surface, hence the common name.",
    },
    malagasyRainbowFrog: {
        id: 29,
        commonName: "Malagasy rainbow frog",
        scientificName: "Scaphiophryne gottlebei",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/d/d1/Scaphiophryne_gottlebei02.jpg",
        info: "The Malagasy rainbow frog is a small, roundish, brightly coloured species with a distinctive white, orange–red, green and black pattern on the back, each area of which is clearly delineated.",
    },
    brunoCasqueHeadedFrog: {
        id: 30,
        commonName: "Bruno's casque headed frog",
        scientificName: "Nyctimantis brunoi",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Perereca-de-capacete_-_Aparasphenodon_brunoi.jpg",
        info: "The head is broad and flattened with a long pointed snout. The eyes are prominent and forward-facing. It has an array of sharp, pointed projections on the head, and the skin on the head is fused to the skull.",
    },
    emeiMustacheFrog: {
        id: 31,
        commonName: "Emei mustache frog",
        scientificName: "Leptobrachium boringii",
        imgSrc: "https://upload.wikimedia.org/wikipedia/commons/b/b9/Hudson_Fu_PLoS_ONE_2013_Leptobrachium_boringii_A.jpg",
        info: "Male Leptobrachium boringii exhibit conspicuous keratinized nuptial spines that grow on their upper lip during the breeding season—these are the \"moustache\" and \"spines\" referred to in its common names.",
    },
}

export default frogs